### ISSUE TITLE
[Bug] ios safari，when press enter at first line in code fence，will delete the line

### ISSUE THREAD

**Issue by yansaid** [Saul-Mirone/milkdown#200] opened 2021-11-25 07:13 UTC
ios safari，load the https://milkdown.dev/#/getting-started

then will happend

https://user-images.githubusercontent.com/12773446/143396620-57d70976-f6c5-4379-a22a-75f08d1bd39a.MP4

**Comment by Saul-Mirone** [comment] 2021-11-25 08:43
Let me have a look

**Comment by Saul-Mirone** [comment] 2021-11-26 03:22
Seems it's a prosemirror bug, I'll open a issue for them.

**Comment by yansaid** [comment] 2021-11-26 07:51
thanks for reply，can you link it here?

**Comment by Saul-Mirone** [comment] 2021-12-02 16:49
I need some help because I still cann't find the root cause, asked in community here:
https://discuss.prosemirror.net/t/bug-ios-safari-when-press-enter-at-first-line-in-code-fence-will-delete-the-line/4249

**Comment by Saul-Mirone** [comment] 2021-12-02 17:52
Also, I find the same issue on riprap, so I think, it's really a prosemirror bug.

**Comment by philippkuehn** [comment] 2021-12-02 18:05
Interestingly, this only happens in the vue version of tiptap. the react demo works as expected 🤔

**Comment by Saul-Mirone** [comment] 2021-12-02 23:30
Fixed by: https://github.com/Saul-Mirone/milkdown/commit/01d9cd3e3b738addc9182a8c8d2e9a8e8cbe926b

I finally find something, it's caused by HTML structure of the code block, if it's:
```html
<pre>
  <code>
  Code Snippets....
  </code>
</pre>
```

Then it will trigger the bug. What I did is insert a `div` after the code tag:
```html
<pre>
  <code>
    <div>
    Code Snippets....
    </div>
  </code>
</pre>
```

**Closed by Saul-Mirone** 2021-12-02 23:30 UTC
Labels: bug

**Comment by yansaid** [comment] 2021-12-06 02:58
> Fixed by: [01d9cd3](https://github.com/Saul-Mirone/milkdown/commit/01d9cd3e3b738addc9182a8c8d2e9a8e8cbe926b)
> 
> I finally find something, it's caused by HTML structure of the code block, if it's:
> 
> ```
> <pre>
>   <code>
>   Code Snippets....
>   </code>
> </pre>
> ```
> 
> Then it will trigger the bug. What I did is insert a `div` after the code tag:
> 
> ```
> <pre>
>   <code>
>     <div>
>     Code Snippets....
>     </div>
>   </code>
> </pre>
> ```

thanks
