### ISSUE TITLE
[Bug] editorViewOptionsCtx must be set for clipboard extension

### ISSUE THREAD

**Issue by echarles** [Saul-Mirone/milkdown#190] opened 2021-11-12 13:25 UTC
**Describe the bug**

To ensure markdown is pasted with format, the `editorViewOptionsCtx` property must be set in the context.

If it is not set, the paste action with format (Cmd+Shift+v on MacOs) will result in plain text (loosing markdown format).

See also https://github.com/Saul-Mirone/milkdown/issues/155

```javascdript
Editor.make()
  .config((ctx) => {
    ctx.set(defaultValueCtx, "# Milkdown :heartpulse: Vanilla");
    ctx.set(editorViewOptionsCtx, { editable: () => true }); // If you don't set this, copy/paste will not keep markdown format.
  })
  .use(nord)
  .use(commonmark)
  .use(clipboard)
  .use(emoji)
  .create();
```

**Comment by Saul-Mirone** [comment] 2021-11-12 14:20
Wired, thanks for your investigation. I think it's related to prosemirror, let me ask them for help.

**Comment by Saul-Mirone** [comment] 2021-11-18 06:42
Still don't know the root cause, but fixed in https://github.com/Saul-Mirone/milkdown/commit/4b37dcfccea8d05b89af45ad02a762687c7d3c44

**Comment by echarles** [comment] 2021-11-18 07:14
Thx. This would more like a workaround. Maybe good to add a comment to the line you have added linking to this issue?

**Comment by Saul-Mirone** [comment] 2021-11-18 07:29
> Thx. This would more like a workaround. Maybe good to add a comment to the line you have added linking to this issue?

Good idea.

**Comment by Saul-Mirone** [comment] 2021-11-18 07:31
Done

**Closed** 2021-11-18 13:14 UTC
Labels: bug
