### ISSUE TITLE
[Bug] Maybe there is a memory leak

### ISSUE THREAD

**Issue by bluesaiz** [Saul-Mirone/milkdown#431] opened 2022-03-23 01:20 UTC
**Describe the bug**
In the demo site, I found that the milkdown may has a memory leak.
**To Reproduce**

1. Go to '[demo site](https://milkdown.dev/zh-hans/online-demo)'
2. Click on switch mode button from light to dark , then switch back.
3. repeat step 2 many times
4. You will find that the memory keeps growing

**Expected behavior**
Memory usage does not increase significantly.

**Screenshots**
![image](https://user-images.githubusercontent.com/40681310/159602992-363a3e29-e9cf-415a-96a8-069df002c0c2.png)

**Desktop (please complete the following information):**

-   OS:  Linux
-   Browser  chrome
-   Version 5.5.0

**Comment by Saul-Mirone** [comment] 2022-03-23 02:39
Should be fixed by https://github.com/Saul-Mirone/milkdown/commit/556890846078c1445c87192375d23cbaaee20bff

**Comment by bluesaiz** [comment] 2022-03-23 06:43
I paste a large markdown document into milkdown, then delete all the content, then paste the some document, and then press redo and undo alternately without interruption, and I will also find that the memory continues to increase.

![image](https://user-images.githubusercontent.com/40681310/159639013-7b3384d8-cb6e-4666-9824-30564e029d34.png)

**Comment by Saul-Mirone** [comment] 2022-03-23 07:51
I think in this case. It makes sense cause the history stack increased. But I do observed some uncleared event listeners in the first case.

**Comment by bluesaiz** [comment] 2022-03-24 01:32
if I just click the undo and redo buttons, the history stack will increase, and the memory will increase significantly, which may also be a bug. 
It is expected that there should be no memory increase.

**Comment by bluesaiz** [comment] 2022-03-24 01:40
I also found another bug, if I kept hitting the undo button, I found that eventually the redo button would disappear.
![image](https://user-images.githubusercontent.com/40681310/159824805-0e41b3a2-6ae7-4341-81af-44498e4f0b6c.png)

**Comment by Saul-Mirone** [comment] 2022-03-24 02:43
> I also found another bug, if I kept hitting the undo button, I found that eventually the redo button would disappear. ![image](https://user-images.githubusercontent.com/40681310/159824805-0e41b3a2-6ae7-4341-81af-44498e4f0b6c.png)

That's not a bug. That means there's no possible redo for your content. For example it already hold the initial content or reach the history limit.

**Comment by Saul-Mirone** [comment] 2022-03-24 02:45
> 

The memory will growth because you're saving states into history stack. You can try any promsemirror based editors. They all have same behavior. If you think about it, how can you avoid use memory if you're adding snapshots in a history stack?

**Comment by Saul-Mirone** [comment] 2022-03-24 02:46
Closing due to fix:
https://github.com/Saul-Mirone/milkdown/commit/bd5b93e05cafc745986831507d5f0c7bc7f4f401
https://github.com/Saul-Mirone/milkdown/commit/da3d2756d39e08df32d39566dcb7428f9e1b59c4
https://github.com/Saul-Mirone/milkdown/commit/556890846078c1445c87192375d23cbaaee20bff

**Closed by Saul-Mirone** 2022-03-24 02:46 UTC
Labels: bug
