### ISSUE TITLE
[Bug] render duplicate dom 

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#470] opened 2022-04-26 13:24 UTC
**Describe the bug**

**To Reproduce**

1. make `useEditor` update depends `options`, and update options very soon ,like my demo code, update once in useEffect
2. render twice 

```ts 

export const Milkdown: React.FC<{ value: string }> = ({ value }) => {
    const ref = React.useRef({} as EditorRef);
    const [options, setOptions] = useState({});
    useEffect(() => {
        setOptions({});
    }, []);
    const editor = useEditor(
        (root, renderReact) => {
            const nodes = commonmark
                .configure(paragraph, { view: renderReact(Paragraph) })
                .configure(blockquote, { view: renderReact(Blockquote, { as: 'section' }) })
                .configure(image, { view: renderReact(Image) })
                .configure(link, { view: renderReact(Link) });

            return Editor.make()
                .config((ctx) => {
                    ctx.set(rootCtx, root);
                    ctx.set(defaultValueCtx, value);
                })
                .use(nord)
                .use(nodes);
        },
        [options],
    );

    return <ReactEditor ref={ref} editor={editor} />;
};
```
**Expected behavior**

**Screenshots**
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/4401981/165309313-aaecc14b-4916-4069-91e3-0de7b16f3016.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/4401981/165309269-0b0ce922-5c83-4587-a6e2-e50bbf8037a8.png">

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by Saul-Mirone** [comment] 2022-04-26 14:29
It's an old bug and has been fixed in v6.0. It's in beta version now and wil be released soon.

**Closed by Saul-Mirone** 2022-04-26 14:29 UTC
Labels: bug

**Comment by 4-1-1** [comment] 2022-04-27 00:08
> It's an old bug and has been fixed in v6.0. It's in beta version now and wil be released soon.

But I just find it in this main branch with 6.0.0.next.1 😢

**Comment by Saul-Mirone** [comment] 2022-04-27 09:32
It's caused by you create the second editor before first editor initialize finished. You can check it before creation like following example:

```typescript
export const Milkdown: React.FC<{ value: string }> = ({ value }) => {
    const ref = React.useRef({} as EditorRef);
    const [options, setOptions] = useState({});

    const isEditorReady = useCallback(() => ref.current.get() != null, []);

    useEffect(() => {
        if (isEditorReady()) {
            setOptions({});
        }
    }, [isEditorReady]);

    const editor = useEditor(
        (root, renderReact) => {
          //...
        },
        [options],
    );

    return <ReactEditor ref={ref} editor={editor} />;
};
```

**Comment by 4-1-1** [comment] 2022-04-27 12:14
Ok ,thanks

**Comment by leangseu** [comment] 2022-05-11 11:29
I had similar situation. For my case it was `React.StrictMode` invoke `useEffect` multiple time and the component didn't get destroy. My work around is:

```js
export const MilkdownEditor = () => {
  const ref = useRef(null);

  useEffect(() => {
    Editor.make()
      .config((ctx) => {
        const node = document.createElement('div');
        ref.current.appendChild(node)
        ctx.set(rootCtx, node);
        ctx.set(defaultValueCtx, "# test");
      
      .use(nord)
      .use(commonmark)
      .create();

      return () => ref.current.removeChild(ref.current.children[0]);
  }, []);

  return <div ref={ref}></div>;
};
```

**Comment by Saul-Mirone** [comment] 2022-05-12 02:47
https://github.com/Saul-Mirone/milkdown/blob/main/packages/react/src/Editor.tsx#L40
You need to call `view.destroy`

**Comment by Saul-Mirone** [comment] 2022-05-12 02:48
> I had similar situation. For my case it was `React.StrictMode` invoke `useEffect` multiple time and the component didn't get destroy. My work around is:
> 
> ```js
> export const MilkdownEditor = () => {
>   const ref = useRef(null);
> 
>   useEffect(() => {
>     Editor.make()
>       .config((ctx) => {
>         const node = document.createElement('div');
>         ref.current.appendChild(node)
>         ctx.set(rootCtx, node);
>         ctx.set(defaultValueCtx, "# test");
>       
>       .use(nord)
>       .use(commonmark)
>       .create();
> 
>       return () => ref.current.removeChild(ref.current.children[0]);
>   }, []);
> 
>   return <div ref={ref}></div>;
> };
> ```

https://github.com/Saul-Mirone/milkdown/blob/main/packages/react/src/Editor.tsx#L40
You need to call `view.destroy`

**Comment by tbdsux** [comment] 2023-07-04 06:56
How to fix this problem with the latest version? 

In my case, I hide and re-show the editor.

**Comment by knownasilya** [comment] 2023-08-10 17:32
Seeing the same with HMR (not react 18). I have a cleanup hook

```
  // Cleanup editor on unmount
  useEffect(() => {
    return () => {
      get()?.destroy();

      if (linkObserver) {
        linkObserver.disconnect();
      }
    };
  }, []);
```

I'm assuming the old one isn't unmounted. Do I need to do memo for `useEditor`? Any examples in v7?
