### ISSUE TITLE
[Feature] I copied the contents of other markdown into milkdown. The format is lost.

### ISSUE THREAD

**Issue by zp941128** [Saul-Mirone/milkdown#155] opened 2021-10-07 13:37 UTC
I copied the contents of other markdown into milkdown. The format is lost。

**Comment by zp941128** [comment] 2021-10-08 01:21
Does the picture support local upload?

**Comment by Saul-Mirone** [comment] 2021-10-08 03:22
> I copied the contents of other markdown into milkdown. The format is lost。

Please provide a example content that can reproduce.

**Comment by zp941128** [comment] 2021-10-08 09:24
>  MDeJXiqyll.mp4 
> 我仍然无法重现这个......

Can you send me the online path? Let me see why

thank you very much indeed

**Comment by Saul-Mirone** [comment] 2021-10-09 02:13
I'll close this issue first, feel free to reopen if you need this.

**Closed by Saul-Mirone** 2021-10-09 02:13 UTC

**Comment by zp941128** [comment] 2021-11-02 15:12
> > 图片支持本地上传吗？
> 
> 不，目前不支持，用户需要创建插件来执行此操作。

hi 

> > Does the picture support local upload?
> 
> No, it's not supported for now and users need to creat plugins to do this.

hi,The latest code support?

**Comment by Saul-Mirone** [comment] 2021-11-02 15:40
> > > Does the picture support local upload?
> > 
> > 
> > No, it's not supported for now and users need to creat plugins to do this.
> 
> hi,The latest code support? I thought you were on the plan last time

You can use this plugin now: https://github.com/Saul-Mirone/milkdown/tree/main/packages/plugin-upload

**Comment by zp941128** [comment] 2021-11-03 06:09
> You can use this plugin now: https://github.com/Saul-Mirone/milkdown/tree/main/packages/plugin-upload

Sorry to bother you again。 install @milkdown/plugin-upload. An error is reported in the node_models
![image](https://user-images.githubusercontent.com/45097782/140016113-6a279945-5e96-4d79-b943-6ca3901965db.png)

then I install @milkdown/utils. This causes an error in the milkdown of the page
error: Uncaught (in promise) TypeError: Object(...) is not a function

**Comment by Saul-Mirone** [comment] 2021-11-03 06:20
> > You can use this plugin now: https://github.com/Saul-Mirone/milkdown/tree/main/packages/plugin-upload
> 
> 
> 
> Sorry to bother you again。 install @milkdown/plugin-upload. An error is reported in the node_models
> 
> ![image](https://user-images.githubusercontent.com/45097782/140016113-6a279945-5e96-4d79-b943-6ca3901965db.png)
> 
> 
> 
> then I install @milkdown/utils. This causes an error in the milkdown of the page
> 
> error: Uncaught (in promise) TypeError: Object(...) is not a function
> 
> 

Please update all milkdown packages to the latest and try again.

**Comment by echarles** [comment] 2021-11-11 10:26
@Saul-Mirone I can reproduce the markdown paste issue. Copying from a VSCode markdown file to latest mildown does not render as you have shown in https://github.com/Saul-Mirone/milkdown/issues/155#issuecomment-938482673

On this gif, I am launching mildown with `pnpm start` and copy/paste from a VSCode markdown file. The pasted text is rendered as plaintext which is not what a user would expect.

Should this issue be reopened?

![Untitled](https://user-images.githubusercontent.com/226720/141282111-21ac6c95-2d28-47f9-9869-891532174ba3.gif)

**Comment by Saul-Mirone** [comment] 2021-11-11 10:38
> @Saul-Mirone I can reproduce the markdown paste issue. Copying from a VSCode markdown file to latest mildown does not render as you have shown in https://github.com/Saul-Mirone/milkdown/issues/155#issuecomment-938482673
> 
> 
> 
> On this gif, I am launching mildown with `pnpm start` and copy/paste from a VSCode markdown file. The pasted text is rendered as plaintext which is not what a user would expect.
> 
> 
> 
> Should this issue be reopened?
> 
> 
> 
> ![Untitled](https://user-images.githubusercontent.com/226720/141282111-21ac6c95-2d28-47f9-9869-891532174ba3.gif)
> 
> 

I'm not sure the reason, but if you use Ctrl/Cmd + v to copy content instead of mouse, it works. Is it something related to vscode?

**Comment by echarles** [comment] 2021-11-11 10:45
> I'm not sure the reason, but if you use Ctrl/Cmd + v to copy content instead of mouse, it works. Is it something related to vscode?

I have tried with Cmd+c in VSCode, then Cmd+v in Milkdown and it does not work either.
I have tried in Chrome and Firefox, and got same issue.
I have tried to copy from a markdown file opened in RStudio, same issue...

**Comment by Saul-Mirone** [comment] 2021-11-11 12:24
> > I'm not sure the reason, but if you use Ctrl/Cmd + v to copy content instead of mouse, it works. Is it something related to vscode?
> 
> I have tried with Cmd+c in VSCode, then Cmd+v in Milkdown and it does not work either. I have tried in Chrome and Firefox, and got same issue. I have tried to copy from a markdown file opened in RStudio, same issue...

Sorry, my bad, the clipboard plugin broken. I've fixed it through: https://github.com/Saul-Mirone/milkdown/commit/366d827f271be52560e7d34fa7ff2841cec1c9fd
The online demo has been fixed. And I'll release this change soon.

**Comment by echarles** [comment] 2021-11-11 13:48
> Sorry, my bad, the clipboard plugin broken. I've fixed it through: 366d827
> The online demo has been fixed. And I'll release this change soon.

Thx a lot for this really quick fix.

I have just tried, and now it works using `Paste and match style`, but not with `Paste`.
This may be the expected behavior?

<img width="467" alt="Screenshot 2021-11-11 at 14 46 51" src="https://user-images.githubusercontent.com/226720/141309001-867dca39-0063-4d68-be8a-2abe60219898.png">

**Comment by Saul-Mirone** [comment] 2021-11-11 14:02
> > Sorry, my bad, the clipboard plugin broken. I've fixed it through: [366d827](https://github.com/Saul-Mirone/milkdown/commit/366d827f271be52560e7d34fa7ff2841cec1c9fd)
> > The online demo has been fixed. And I'll release this change soon.
> 
> Thx a lot for this really quick fix.
> 
> I have just tried, and now it works using `Paste and match style`, but not with `Paste`. This may be the expected behavior?
> 
> <img alt="Screenshot 2021-11-11 at 14 46 51" width="467" src="https://user-images.githubusercontent.com/226720/141309001-867dca39-0063-4d68-be8a-2abe60219898.png">

I don't have this option in windows 😢 , maybe it's related to the browser functionality? I'm not sure. What's the behavior of Cmd + v from your side?

**Comment by echarles** [comment] 2021-11-11 15:23
> I don't have this option in windows 😢 , maybe it's related to the browser functionality? I'm not sure. What's the behavior of Cmd + v from your side?

A simple Cmd+v does not work on my Mac. However Cmd+Shift+v works well on Chrome and Firefox.

Maybe on Windows you have by default the paste with style. There should be subtle notions I don't master, read e.g.
 
https://www.howtogeek.com/fyi/tired-of-pasted-text-messing-up-your-formatting-try-this/
